### PR TITLE
Release 1.3.2

### PR DESCRIPTION
**Pull request by Dinamiko**
- Fix - Improve Subscription plugin support. #161
- Fix - Disable vault setting if vaulting feature is not available. #150
- Fix - Cast item get_quantity into int. #168
- Fix - Fix Credit Card form fields placeholder and label. #146
- Fix - Filter PayPal-supported language codes. #154
- Fix - Wrong order status for orders with contain only products which are both virtual and downloadable. #145
- Fix - Use order_number instead of internal id when creating invoice Id. #163
- Fix - Fix pay later messaging options. #141
- Fix - UI/UX for vaulting settings. #166

### CODE REVIEW

**Comment by Dinamiko** [comment]
Hi @jorgeatorres @mattallan,

Release 1.3.2 PR is ready, it includes vaulting and Subscription improvements and fixes among other bug fixes. If you have any doubt please let me know, thanks.

Note that it does not include the release date yet on `changelog.txt`.

**Comment by mattallan** [comment]
Hi @Dinamiko,

I tested this release today and didn't notice any major issues with this. Here's what I tested:

- [x] `* Fix - Improve Subscription plugin support`
  - [x] Scenario change subscription payment from another payment to an existing saved credit card
    - To test: Add two saved cards and tried to change the payment method from my account page
  - [x] Scenario renewal subscription uses the correct payment`
    - To test: After changing the payment method to a different card, trigger a renewal and log into PP Sandbox to check the last 4 card number (there's probably a simpler way of testing this)
 - [x] `* Fix - Credit Card form fields placeholder and label`
 - [ ] `* FIx - UI/UX for vaulting settings`
   - How do I test this? I tried creating a new Sandbox account with vaulting not enabled but when I connected it to my store, vaulting gets enabled by default. There were some SB accounts I've connected and the vaulting option in settings was disabled but I couldn't reproduce this recently.

---

I had a bit of trouble testing this release, but it turns out the test cards I was using were causing the problems...

Here's the only [two vault cards ](https://developer.paypal.com/docs/limited-release/vault-payment-methods/vault-sdk/#test-cards)that worked for me (and maybe for you too):
`4500600000000061`
`4012888888881881`

**Comment by Dinamiko** [comment]
Hi @mattallan, thanks for testing!

> FIx - UI/UX for vaulting settings
> How do I test this? I tried creating a new Sandbox account with vaulting not enabled but when I connected it to my store, vaulting gets enabled by default. There were some SB accounts I've connected and the vaulting option in settings was disabled but I couldn't reproduce this recently.

We´ve added `VAULT` in api integration (https://github.com/woocommerce/woocommerce-paypal-payments/blob/cc1cd30bb52e101604ab9f6ad83aa27b2ee3f0d9/modules/ppcp-api-client/src/Repository/class-partnerreferralsdata.php#L109) so now vaulting will be automatically enabled on PayPal at onboarding time, this is a bit tricky to test because it will disable the setting only if it fails when enabling it on PayPal, so if the vaulting setting is enabled in your case, it means that is correctly enabled on PayPal otherwise it would be disabled.

> Here's the only two vault cards that worked for me (and maybe for you too):

Same, for me only MasterCard and Visa numbers from that Vaulting documentation page seems to work.

**Comment by jorgeatorres** [comment]
Hi @Dinamiko!

This looks good. Thank you!
I believe we can finetune certain UI details related to the vaulting/Pay Later settings but I don't want to hold off the release because of that. I'll open a new issue so that we can discuss.

Once again, thank you for all the work that went into this release.

**Review by jorgeatorres — APPROVED** [review]
LGTM.

**Pull request merged**
