### PR TITLE
Do not add pay later button in editor (3535)

### LINKED ISSUE #2515: Multiple PayPal buttons are rendered in one express payment container (3535)
### Describe the Bug

In the express checkout section of the Checkout block, PayPal renders 2 buttons instead of 1, if both PayPal and PayLater are enabled. Only 1 button should be rendered with each call to `registerExpressPaymentMethod`.

### To Reproduce

1. Enable both PayPal and Pay Later buttions
2. Go to the Checkout block in the editor
3. See that 2 buttons are rendered vertically in one grid item, breaking the layout. 

### Screenshots

Screenshot 2024-08-14 at 10 00 09

### Expected Behavior

I would expect only 1 button to be rendered per slot.

### Actual Behavior

2 (or possible more?) buttons are rendered in the same grid slot

### Environment

WC 9.2 - but test with latest WC trunk if you can, it includes some updates to the express checkout area that make this bug more prominent.

### PR DESCRIPTION
**Pull request by AlexP11223**
In 4e34332c0bb47 we removed all APMs in editor because it is difficult to determine which APMs are available when registering buttons separately in editor, `canMakePayment` does not work there.

But `fundingSource` was not set to `paypal`, so it could still render at least Pay Later button (in the same express payment method cell, breaking layout when there are other methods).

Fixed that, now only one PayPal button can be shown in editor.

### CODE REVIEW

**Review by stracker-phil — APPROVED** [review]

**Comment by alexflorisca** [comment]
Hey there, just checking up on this PR as it was ready to merge a month ago? Is there a reason it hasn't yet? \cc @InpsydeNiklas

**Comment by InpsydeNiklas** [comment]
@alexflorisca We found some remaining edge-case issues where incorrect buttons were displayed in the editor, which seemed more difficult to resolve. However, we merged this now and will include it with #2448 in the upcoming 2.9.4 update.

**Comment by alexflorisca** [comment]
Thanks @InpsydeNiklas. Just to be annoying, I think the best UX would be to render the PayLater button as a separate button, if it's enabled in the backend. Otherwise the merchant and shopper UX will be different!

Editor: 
Screenshot 2024-11-01 at 16 40 37

Frontend:
Screenshot 2024-11-01 at 16 40 10

(You can see similar discrepancies with WooPayments too).

It would be great to address this too.

**Comment by InpsydeNiklas** [comment]
@alexflorisca I completely agree! Disabling the non-PayPal buttons (which also includes Venmo) is more of a temporary workaround to prevent the layout in the editor from breaking. 
The problem is that the buttons rendered in the editor are using the `PayPalButtons` component from the PayPal React library. However, as far as I am aware, this component currently does not allow us to split the buttons into individual ones, like how it works in the frontend. We continue to look for ways to make it work, but it won't be ready for this release cycle, so we settled on this workaround for now.

**Comment by AlexP11223** [comment]
Splitting may be possible (or we can try again to use the same library as in frontend), but the main problem is determining which buttons are available (e.g. for the merchant/shop country). 

In frontend we use `canMakePayment` with async promises, but in editor it is not called for some reason. https://github.com/woocommerce/woocommerce-paypal-payments/blob/0b6e04d0688e063327127b1d010500c15faff860/modules/ppcp-blocks/resources/js/checkout-block.js#L826-L845

So unless there is a way to get something like `canMakePayment` in editor, we would need to figure out some other way to determine the buttons availability earlier (before the express methods registration, e.g. on the server side) without the PayPal JS SDK.

**Comment by alexflorisca** [comment]
@AlexP11223 I see, we don't currently run the `canMakePayment` function in the editor, but I think it might be wise to do so if we want to create parity with the front-end in terms of which buttons are displayed. I've brought it up with my team for discussion and I'll let you know what we decide.

**Comment by alexflorisca** [comment]
After talking it through with a colleague, we think you should be able to do this outside of the `canMakePayment` method. You can pass a different component as the `edit` prop when you initialise the express payment method, so this should be able to handle the process of initialising the buttons without `canMakePayment` being called. 

It's also  worth noting that in the editor, we have preview data, which is always a US based store with USD as the currency. So this may or may not affect what you render. The ideal situations here is to match the settings configured by the merchant ( e.g. number of buttons configured in the PayPal settings) and display these in the editor, ignoring shop location/country and bypassing any other conditional logic for wether the buttons load or not.

**Comment by stracker-phil** [comment]
Hi @alexflorisca thanks for those inputs. Those sound like reasonable changes to me, so I've gone ahead and created an internal issue for your suggestion, and we'll discuss it in the next planning session.

**Pull request merged**
