### PR TITLE
Add QIT Custom E2E support and migrate tests

### LINKED ISSUE #2723: Add QIT E2E Integrations Tests
With the availability of [new QIT: Custom tests](https://10upwoo.wordpress.com/2024/07/17/whats-new-in-qit-custom-tests/) the goal of this task is to identify the approach and add the QIT E2E integration tests.

Docs: https://qit.woo.com/docs/category/custom-e2e-tests/

### PR DESCRIPTION
**Pull request by iamdharmesh**
**Issue**: #2723 
---

### Description
This PR introduces initial support for QIT Custom E2E tests and migrates existing E2E tests to the QIT framework, enabling them to run in the QIT environment.

This is the first step towards adding integration tests to the workflow. QIT Custom E2E tests allow us to run tests for other plugins. This enables us to check plugin compatibility by running tests with specific plugins activated and configured.

### Key Changes  

- **Support for QIT Custom E2E Tests**: Added QIT integration to enable Custom E2E testing.  
- **Migration of Existing E2E Tests**: Migrated current tests to QIT and added GitHub Action workflow for run E2E tests
- **Initial Compatibility Testing**: Implemented compatibility tests with the "WooCommerce Stripe Payment Gateway" plugin in GitHub Action.  
- **New Workflow for Upload test tags**: Added a GitHub Action workflow to upload test tags to QIT upon release. Tests are categorized into:  
  - **`default`**: All E2E tests.  
  - **`subscriptions-tests`**: Tests for subscriptions functionality.
  
> [!NOTE]
Some E2E tests are skipped because they require an in-depth checking of the current errors they encounter. Therefore, they are excluded from this initial PR and can be revisited later.

### Steps to Test
1. Run `npm run build`.
1. Copy the file `/tests/qit-e2e/config/.env.example` to `/tests/qit-e2e/config/.env`.
1. Add the credentials in the `.env` file.
1. Run `npm run test:e2e-local` and make sure that tests are running properly and are passing.
1. Make sure that the "QIT E2E tests" action is passing. (This is PR from fork repo so, This GH action will not successfully run here, you can verify it from PR [here](https://github.com/iamdharmesh/woocommerce-paypal-payments/pull/1)) 

### Documentation

- [ ] This PR needs documentation (has the "Documentation" label).

### Changelog Entry

> Dev - Added QIT Custom E2E tests support and migrated tests to QIT

Closes #2723.

### CODE REVIEW

**Comment by iamdharmesh** [comment]
@dkotter I am not able to request a review from you due to access constraints here, But this is ready for your review.

**Review by dkotter — APPROVED** [review]

**Comment by vikrampm1** [comment]
@woocommerce/quark this PR is ready for your review (we have limited access and unable to request review).

**Comment by jeffpaul** [comment]
@zhongruige @luc45 FYI this is also up for your review on approach / code review feedback

**Comment by annemirasol** [comment]
@iamdharmesh @vikrampm1 To avoid impacting development that are currently underway for Stripe and Paypal, we created a new repo for hosting the new QIT tests. Could we move these tests to https://github.com/woocommerce/woocommerce-gateway-integration-qit, please? 

cc @diegocurbelo

**Comment by jeffpaul** [comment]
@diegocurbelo is that new repo one that will host ALL integration tests across any combination of extensions?  If so, seems like "gateway" in the repo name won't apply when we start to add coverage to things like Subscriptions, etc.

**Comment by diegocurbelo** [comment]
> @diegocurbelo is that new repo one that will host ALL integration tests across any combination of extensions? If so, seems like "gateway" in the repo name won't apply when we start to add coverage to things like Subscriptions, etc.

Let's use the new repo for now; we can always rename it later. Subscriptions in particular is very coupled to the payment gateways...  we even have it as a dependency for E2E tests in some repos, so adding the integration tests with Subscriptions in the new repo seems ok.

We need to draw the line somewhere, and for now, payment gateways make the most sense.
If/when we add tests with different themes or checkout builders for example, we'll most likely need to split the tests in different repos, or have just one big "monorepo".

**Comment by iamdharmesh** [comment]
Closing in favour of PR https://github.com/woocommerce/woocommerce-gateway-integration-qit/pull/2

**Pull request closed without merging**
